name: my Workflow
on: workflow_dispatch

permission:
  id-token: write
  contents: read
jobs: 
  Terraform-init-plan: 
  runs-on: newrunner
  steps: 
  - name: Checkout
    uses: actions/checkout@v5.0.0
